config/routes.rb
Rails.application.routes.draw do
  root to: 'lyrics#new'
  resources :lyrics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lyric.rb
class Lyric < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lyrics_controller.rb
class LyricsController < ApplicationController
  before_action :set_lyric, only: [:show, :edit, :update, :destroy]

  # GET /lyrics
  def index
    @lyrics = Lyric.all
  end

  # GET /lyrics/1
  def show
  end

  # GET /lyrics/new
  def new
    @lyric = Lyric.new
  end

  # GET /lyrics/1/edit
  def edit
  end

  # POST /lyrics
  def create
    @lyric = Lyric.new(lyric_params)

    if @lyric.save
      redirect_to @lyric, notice: 'Lyric was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /lyrics/1
  def update
    if @lyric.update(lyric_params)
      redirect_to @lyric, notice: 'Lyric was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /lyrics/1
  def destroy
    @lyric.destroy
    redirect_to lyrics_url, notice: 'Lyric was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lyric
      @lyric = Lyric.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def lyric_params
      params.require(:lyric).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lyrics_helper.rb
module LyricsHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown_to_html(source)
    Kramdown::Document.new(source, input: 'GFM').to_html
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Rhymers Delight
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
  body
    div
      p#notice
        = flash[:notice]
      p#alert
        = flash[:alert]
    .logo
      | Rhymers Delight
    main
      = yield

app/views/lyrics/_form.html.slim
.col-xs-6
  h1 Lyric
  = form_for @lyric do |f|
    - if @lyric.errors.any?
      #error_explanation
        h2 = "#{pluralize(@lyric.errors.count, "error")} prohibited this lyric from being saved:"
        ul
          - @lyric.errors.full_messages.each do |message|
            li = message
    .form-group
      #rhyme-editor
    .actions
      = f.submit

.col-xs-6
  h1 Rhyme
  .lyric
    .lyric__body
      #rhyme

javascript:
  window.RhymeMachine = (new window.RhymeEditor.RhymeEditor(document.getElementById('rhyme-editor'), #{{@lyric.to_json}})).render()

app/views/lyrics/_rhyme.html.slim
- if body.present?
  == markdown_to_html(lyric_to_rhyme(body))

app/views/lyrics/edit.html.slim
h1 Editing lyric

== render 'form'

= link_to 'Show', @lyric
'|
= link_to 'Back', lyrics_path

app/views/lyrics/index.html.slim
h1 Listing lyrics

table
  thead
    tr
      th Body
      th
      th
      th

  tbody
    - @lyrics.each do |lyric|
      tr
        td = lyric.body
        td = link_to 'Show', lyric
        td = link_to 'Edit', edit_lyric_path(lyric)
        td = link_to 'Destroy', lyric, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Lyric', new_lyric_path

app/views/lyrics/new.html.slim
.container
  .row
    == render 'form'

= link_to 'Back', lyrics_path

app/views/lyrics/show.html.slim
p#notice = notice

p
  strong Body:
  = @lyric.body

= link_to 'Edit', edit_lyric_path(@lyric)
'|
= link_to 'Back', lyrics_path